### ISSUE TITLE
Add additional netplan keys for wifi  (ubuntu)

### ISSUE THREAD

**Issue by mmattel** [raspberrypi/rpi-imager#459]
When installing an OS that uses netplan like U22.04 server via the imager, you get asked about the WIFI data which is then written to the netplan config file. Two suggestions to add:

* First add the `optional: true` key which deblocks booting when the access point is down.
* Add a new field in the imager to ask if the WIFI is hidden and add in case the `hidden: true` option in the netplan config. Else you get a hard time finding why it does not connect.

See a working example:
```
     wifis:
        wlan0:
            optional: true
            access-points:
                ABCD:
                  password: "*****"
                  hidden: true
...
```
