### ISSUE TITLE
When the wireless LAN is configured, the ethernet adapter is disabled.

### ISSUE THREAD

**Issue by sotnyk-lv** [raspberrypi/rpi-imager#571]
Hi!
While configuring the Ubuntu server, I noticed that if the wireless LAN is configured in the Advanced options popup, the wired connection is disabled. 

It is unclear behavior.

The network configuration file is erased and replaced with something like this:
```
    wifis:
        renderer: networkd
        wlan0:
            access-points:
                SSID:
                    password: PASSKEY
            dhcp4: true
            optional: true
```
https://github.com/raspberrypi/rpi-imager/blob/9e882b31c48f92870750154b144dff17c5fbfe9b/src/OptionsPopup.qml#L738-L749

Shouldn't those settings be appended to the default file, or some other options be added to remain the eth0 connection active?
